### ISSUE TITLE
Reloading native shared libraries for repl style development

### ISSUE THREAD

**Issue by davidpham87** [techascent/tech.jna#4]
Hello,

Thanks a lot for the library, I am trying to play with it and I find it really enjoyable.

I wondered if you would consider adding a `reload-library!` function, which would reload the native library.  

My use case is about discovering C with Clojure in order to get the interactivtiy of Clojure in my learning path. So I would compile back and forth my C code and load it in my Clojure repl. However, without the reload function I was forced to shut down the repl every time.

I came up with this solution that was filling my need, but I am unsure if this would fit in the library:

```clojure
(require  '[tech.jna.base :as base])

(defn reload!
  "Reload a shared library."
  [libname]
  (when-let [native-lib (get @base/*loaded-libraries* libname)]
    (.dispose native-lib)
    (swap! base/*loaded-libraries* dissoc libname)
    (base/do-load-library libname)))
```

Best regards,
David

**Comment by cnuernber** [comment]
Very cool addition.  I am not at all opposed to this with a caveat that your C library's initialization code may not be OK with this type of reloading operation.

Did you test with any statically initialized sections?

**Comment by davidpham87** [comment]
Nope, mostly pure functions. My knowledge of C is probably not good enough to see all possible caveats.

**Comment by cnuernber** [comment]
Initial cut is in: [`[techascent/tech.jna "4.01"]`](https://techascent.github.io/tech.jna/tech.v3.jna.html#var-reload.21).

We also fixed a major issue in tech.resource and now the library is much safer to use.  malloc now binds results to the garbage collector by default as opposed to both gc and stack.
