### ISSUE TITLE
need arm64e

### ISSUE THREAD

**Issue by vaibhawc** [techascent/tech.jna#6]
Was trying out. Got this m1 mac:
`fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')`
Please suggest the options.

**Comment by cnuernber** [comment]
We have moved to using dtype-next's [ffi system](https://cnuernber.github.io/dtype-next/tech.v3.datatype.ffi.html).  It has fixes for m1-mac specifically but you have to include the latest JNA.

See [blogpost](https://techascent.com/blog/next-gen-native.html), [avclj](https://github.com/cnuernber/avclj), and [tmducken](https://github.com/cnuernber/tmducken) for examples.
